In [ ]:
from google.colab import drive
drive.mount('/content/drive')
data_path = '/content/drive/MyDrive/Data Sci CU/Research with Kiatanan//'
# data_path = './'

Mounted at /content/drive

In [ ]:
!pip install pyreadstat

Collecting pyreadstat
  Downloading pyreadstat-1.3.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: narwhals>=2.0 in /usr/local/lib/python3.12/dist-packages (from pyreadstat) (2.11.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pyreadstat) (2.0.2)
Downloading pyreadstat-1.3.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 90.8 MB/s eta 0:00:00
Installing collected packages: pyreadstat
Successfully installed pyreadstat-1.3.2

In [ ]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

In [ ]:
import pandas as pd
import numpy as np
import pyreadstat

In [ ]:
# Create Function for Recall MetaData Detail
import json

def recall_variable(meta_data,name):
  output_list = []
  print(f'Variable Name: {name}')
  print('\n')
  print(meta_data.loc[name,'Label'])
  print('\n')
  if meta_data.loc[name,'Value'] == np.nan:
    print('Value non-identify')
  elif isinstance(meta_data.loc[name,'Value'],dict):
    for key in list(meta_data.loc[name,'Value'].keys()):
      val = meta_data.loc[name,'Value'][key]
      output_list.append((key,val))
    return display(pd.DataFrame(output_list))
  else:
    print(meta_data.loc[name,'Value'])
  print('\n')

# School QQQ Dataset

## Prepare Metadata
`school_meta` is Meta Data for School Dataset

In [ ]:
# Import
school_df, school_meta = pyreadstat.read_sav(data_path + 'CY08MSP_SCH_QQQ.SAV')

# Variable Name and Label
name_label_dict = school_meta.column_names_to_labels
variable = school_meta.variable_value_labels

name_list = []
label_list = []
variable_list = []

for key in list(name_label_dict.keys()):
  name = key
  label = name_label_dict[key]
  name_list.append(name)
  label_list.append(label)

for key in name_list:
  try:
      # ถ้าสามารถ run ได้
      variable_bykey = variable[key]
      variable_list.append(variable_bykey)
  except:
      variable_list.append(None)

# Create Name and Label Dataset
meta_name = pd.DataFrame(name_list,columns=['Name'])
meta_value = pd.DataFrame(name_list,columns=['Name'])

meta_name['Label'] = label_list
meta_value['Value'] = variable_list

# Join meta_name and meta_value
school_meta = pd.merge(meta_name, meta_value, on='Name', how='left')

In [ ]:
school_meta = school_meta.set_index('Name')
school_meta['Name'] = name_list

school_meta = school_meta[['Name','Label','Value']]

In [ ]:
school_meta.info()

<class 'pandas.core.frame.DataFrame'>
Index: 431 entries, CNT to VER_DAT
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    431 non-null    object
 1   Label   431 non-null    object
 2   Value   423 non-null    object
dtypes: object(3)
memory usage: 13.5+ KB

In [ ]:
school_meta.to_excel(data_path+'school_meta_2022.xlsx', index=False)
print('school_meta Wrirt and Upload to Drive')

school_meta Wrirt and Upload to Drive

## Prepare School Dataframe
`school_df` already Dataframe

In [ ]:
school_df

,CNT,CNTRYID,CNTSCHID,CYC,NatCen,STRATUM,SUBNATIO,REGION,OECD,ADMINMODE,...,SCSUPRT,PROBSCRI,SCPREPBP,SCPREPAP,DIGPREP,W_SCHGRNRABWT,W_FSTUWT_SCH_SUM,W_FSTUWT_SCH_N,SENWT,VER_DAT
0,ALB,8.0,800001.0,08MS,000800,ALB05,0080000,800.0,0.0,2.0,...,2.0,0.7965,-0.8314,0.8462,0.5908,1.43376,160.58080,41.0,5.76182,03MAY23:10:11:34
1,ALB,8.0,800002.0,08MS,000800,ALB07,0080000,800.0,0.0,2.0,...,1.0,-0.5687,-0.8314,0.8462,-0.3475,2.85278,133.71140,36.0,11.46442,03MAY23:10:11:34
2,ALB,8.0,800003.0,08MS,000800,ALB06,0080000,800.0,0.0,2.0,...,1.0,0.1896,-0.8314,-0.8711,0.4409,7.40007,25.61079,3.0,29.73857,03MAY23:10:11:34
3,ALB,8.0,800004.0,08MS,000800,ALB05,0080000,800.0,0.0,2.0,...,NaN,NaN,NaN,NaN,-0.7414,4.34319,192.24130,39.0,17.45392,03MAY23:10:11:34
4,ALB,8.0,800005.0,08MS,000800,ALB03,0080000,800.0,0.0,2.0,...,2.0,0.6649,-0.8314,0.8462,-0.0102,7.52060,45.69535,5.0,30.22293,03MAY23:10:11:34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21624,QUR,901.0,90100178.0,08MS,080400,UKR26,9010000,90100.0,0.0,2.0,...,NaN,NaN,NaN,NaN,2.2897,53.75000,459.78720,8.0,40.82246,01MAY23:18:14:40
21625,QUR,901.0,90100179.0,08MS,080400,UKR26,9010000,90100.0,0.0,2.0,...,1.0,0.4590,-0.8314,0.8462,-0.2793,53.75000,280.33170,5.0,40.82246,01MAY23:18:14:40
21626,QUR,901.0,90100180.0,08MS,080400,UKR12,9010000,90100.0,0.0,2.0,...,1.0,0.9920,1.3112,0.8462,0.3470,25.49544,1726.41200,45.0,19.36347,01MAY23:18:14:40
21627,QUR,901.0,90100181.0,08MS,080400,UKR21,9010000,90100.0,0.0,2.0,...,1.0,0.1896,0.7399,0.8462,2.2897,18.33558,1684.65500,48.0,13.92564,01MAY23:18:14:40
21628,QUR,901.0,90100182.0,08MS,080400,UKR14,9010000,90100.0,0.0,2.0,...,1.0,0.3285,1.2019,0.8462,0.1178,23.00685,1234.79500,22.0,17.47341,01MAY23:18:14:40

In [ ]:
school_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21629 entries, 0 to 21628
Columns: 431 entries, CNT to VER_DAT
dtypes: float64(423), object(8)
memory usage: 71.1+ MB

In [ ]:
school_df.to_excel(data_path+'school_df_2022.xlsx', index=False)
print('school_df Wrire and Upload to Drive')

school_df Wrire and Upload to Drive

# Student QQQ Dataset

## Prepare Meta Data

In [ ]:
# Import
student_df, student_meta = pyreadstat.read_sav(data_path + 'CY08MSP_STU_QQQ.SAV')

# Variable Name and Label
name_label_dict = student_meta.column_names_to_labels
variable = student_meta.variable_value_labels

name_list = []
label_list = []
variable_list = []

for key in list(name_label_dict.keys()):
  name = key
  label = name_label_dict[key]
  name_list.append(name)
  label_list.append(label)

for key in name_list:
  try:
      # ถ้าสามารถ run ได้
      variable_bykey = variable[key]
      variable_list.append(variable_bykey)
  except:
      variable_list.append(None)

# Create Name and Label Dataset
meta_name = pd.DataFrame(name_list,columns=['Name'])
meta_value = pd.DataFrame(name_list,columns=['Name'])

meta_name['Label'] = label_list
meta_value['Value'] = variable_list

# Join meta_name and meta_value
student_meta = pd.merge(meta_name, meta_value, on='Name', how='left')

In [ ]:
student_meta

,Name,Label,Value
0,CNT,Country code 3-character,"{'MDA': 'Republic of Moldova', 'THA': 'Thailan..."
1,CNTRYID,Country Identifier,"{8.0: 'Albania', 31.0: 'Baku (Azerbaijan)', 32..."
2,CNTSCHID,Intl. School ID,None
3,CNTSTUID,Intl. Student ID,None
4,CYC,PISA Assessment Cycle (2 digits + 2 character ...,None
...,...,...,...
1273,PV8MPRE,Plausible Value 8 in Process Subscale of Mathe...,None
1274,PV9MPRE,Plausible Value 9 in Process Subscale of Mathe...,None
1275,PV10MPRE,Plausible Value 10 in Process Subscale of Math...,None
1276,SENWT,Senate Weight (sum of 5000 per country),None
1277,VER_DAT,Date of the database creation,None

In [ ]:
student_meta = student_meta.set_index('Name')
student_meta['Name'] = name_list

student_meta = student_meta[['Name','Label','Value']]

In [ ]:
student_meta.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1278 entries, CNT to VER_DAT
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    1278 non-null   object
 1   Label   1278 non-null   object
 2   Value   1081 non-null   object
dtypes: object(3)
memory usage: 39.9+ KB

In [ ]:
import pandas as pd
student_meta.to_excel(data_path+'student_qqq_meta_2022.xlsx')

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

## Prepare School Dataframe
`student_df` already Dataframe

In [ ]:
student_df.shape

(613744, 1278)

In [ ]:
student_df.head(5)

,CNT,CNTRYID,CNTSCHID,CNTSTUID,CYC,NatCen,STRATUM,SUBNATIO,REGION,OECD,...,PV3MPRE,PV4MPRE,PV5MPRE,PV6MPRE,PV7MPRE,PV8MPRE,PV9MPRE,PV10MPRE,SENWT,VER_DAT
0,ALB,8.0,800282.0,800001.0,08MS,000800,ALB03,0080000,800.0,0.0,...,226.250,203.029,219.817,331.017,223.752,305.671,230.156,289.436,0.55561,03MAY23:10:11:25
1,ALB,8.0,800115.0,800002.0,08MS,000800,ALB03,0080000,800.0,0.0,...,298.644,321.405,320.452,284.836,364.565,304.044,347.626,352.269,0.76431,03MAY23:10:11:25
2,ALB,8.0,800242.0,800003.0,08MS,000800,ALB01,0080000,800.0,0.0,...,383.340,376.019,285.901,289.896,338.469,316.296,324.361,343.351,1.37877,03MAY23:10:11:25
3,ALB,8.0,800245.0,800005.0,08MS,000800,ALB08,0080000,800.0,0.0,...,264.532,303.422,327.793,165.575,246.156,238.322,275.860,227.466,1.49361,03MAY23:10:11:26
4,ALB,8.0,800285.0,800006.0,08MS,000800,ALB03,0080000,800.0,0.0,...,399.300,514.739,539.850,461.793,514.465,510.462,490.537,503.793,0.65249,03MAY23:10:11:26

In [ ]:
student_df.to_csv(data_path+'student_qqq_df_2022.csv', index=False)
print('school_df Wrire and Upload to Drive')

school_df Wrire and Upload to Drive

# Teacher QQQ

## Prepare Meta Data

In [ ]:
# Import
teacher_df, teacher_meta = pyreadstat.read_sav(data_path + 'CY08MSP_TCH_QQQ.SAV')

# Variable Name and Label
name_label_dict = teacher_meta.column_names_to_labels
variable = teacher_meta.variable_value_labels

name_list = []
label_list = []
variable_list = []

for key in list(name_label_dict.keys()):
  name = key
  label = name_label_dict[key]
  name_list.append(name)
  label_list.append(label)

for key in name_list:
  try:
      # ถ้าสามารถ run ได้
      variable_bykey = variable[key]
      variable_list.append(variable_bykey)
  except:
      variable_list.append(None)

# Create Name and Label Dataset
meta_name = pd.DataFrame(name_list,columns=['Name'])
meta_value = pd.DataFrame(name_list,columns=['Name'])

meta_name['Label'] = label_list
meta_value['Value'] = variable_list

# Join meta_name and meta_value
teacher_meta = pd.merge(meta_name, meta_value, on='Name', how='left')

In [ ]:
teacher_meta

,Name,Label,Value
0,CNT,Country code 3-character,"{'MDA': 'Republic of Moldova', 'THA': 'Thailan..."
1,CNTRYID,Country Identifier,"{8.0: 'Albania', 31.0: 'Baku (Azerbaijan)', 32..."
2,CNTSCHID,Intl. School ID,None
3,CNTTCHID,Intl. Teacher ID,None
4,CYC,PISA Assessment Cycle (2 digits + 2 character ...,None
...,...,...,...
538,WVARSTRR,RANDOMIZED FINAL VARIANCE STRATUM (1-80),None
539,W_FSTUWT_SCH_SUM,Sum of W_FSTUWT,None
540,W_FSTUWT_SCH_N,N of W_FSTUWT,None
541,SENWT,Senate Weight (sum of 5000 per country),None
542,VER_DAT,Date of the database creation,None

In [ ]:
teacher_meta = teacher_meta.set_index('Name')
teacher_meta['Name'] = name_list

teacher_meta = teacher_meta[['Name','Label','Value']]

print(teacher_meta.info())

<class 'pandas.core.frame.DataFrame'>
Index: 543 entries, CNT to VER_DAT
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    543 non-null    object
 1   Label   543 non-null    object
 2   Value   453 non-null    object
dtypes: object(3)
memory usage: 17.0+ KB
None

In [ ]:
teacher_meta.to_excel(data_path+'teacher_qqq_meta_2022.xlsx')

## Prepare Dataset
`teacher_df` already DataFrame

In [ ]:
display(teacher_df)

,CNT,CNTRYID,CNTSCHID,CNTTCHID,CYC,NatCen,STRATUM,SUBNATIO,REGION,OECD,...,W_FTCHRWT77,W_FTCHRWT78,W_FTCHRWT79,W_FTCHRWT80,UNIT,WVARSTRR,W_FSTUWT_SCH_SUM,W_FSTUWT_SCH_N,SENWT,VER_DAT
0,QAZ,31.0,3100135.0,3100001.0,08MS,003100,QAZ01,0310000,3100.0,0.0,...,5.39034,5.80231,2.65612,1.91078,1.0,9.0,178.54070,41.0,1.31649,01MAY23:17:56:00
1,QAZ,31.0,3100073.0,3100002.0,08MS,003100,QAZ01,0310000,3100.0,0.0,...,4.33145,14.27270,12.98264,13.79469,1.0,43.0,146.41090,30.0,2.94921,01MAY23:17:56:00
2,QAZ,31.0,3100092.0,3100007.0,08MS,003100,QAZ01,0310000,3100.0,0.0,...,16.61777,6.08420,5.53427,17.64129,2.0,51.0,171.57920,40.0,3.77159,01MAY23:17:56:00
3,QAZ,31.0,3100135.0,3100008.0,08MS,003100,QAZ01,0310000,3100.0,0.0,...,8.32923,9.14863,2.77391,2.94741,1.0,9.0,178.54070,41.0,1.89041,01MAY23:17:56:00
4,QAZ,31.0,3100146.0,3100010.0,08MS,003100,QAZ01,0310000,3100.0,0.0,...,1.37347,1.44759,4.15063,4.22618,1.0,54.0,166.06180,41.0,0.89339,01MAY23:17:56:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68049,ARE,784.0,78400154.0,78411931.0,08MS,078402,ARE06,7840100,78400.0,0.0,...,1.50000,0.50000,1.50000,1.50000,2.0,60.0,195.53800,41.0,0.31816,01MAY23:15:46:58
68050,ARE,784.0,78400122.0,78411932.0,08MS,078402,ARE07,7840100,78400.0,0.0,...,1.50000,1.50000,0.50000,0.50000,2.0,77.0,140.27350,36.0,0.31816,01MAY23:15:46:58
68051,ARE,784.0,78400639.0,78411933.0,08MS,078401,ARE01,7840100,78400.0,0.0,...,0.88880,0.84010,0.83240,0.83240,2.0,80.0,221.69160,39.0,0.53215,01MAY23:15:46:58
68052,ARE,784.0,78400020.0,78411934.0,08MS,078401,ARE01,7840100,78400.0,0.0,...,0.56579,1.70833,1.79167,1.92188,1.0,67.0,103.72510,41.0,0.37119,01MAY23:15:46:58
68053,ARE,784.0,78400552.0,78411935.0,08MS,078402,ARE07,7840100,78400.0,0.0,...,1.52318,0.52713,1.57665,1.52471,2.0,33.0,83.95136,38.0,0.32914,01MAY23:15:46:58

In [ ]:
teacher_df.to_csv(data_path+'teacher_qqq_df_2022.csv', index=False)
print('school_df Wrire and Upload to Drive')

school_df Wrire and Upload to Drive

# Student TIM

## Prepare Meta Data

In [ ]:
# Import
data_path = '/content/drive/MyDrive/Data Sci CU/Research with Kiatanan/STU_TIM_SPSS/'
student_tim_df, student_tim_meta = pyreadstat.read_sav(data_path + 'CY08MSP_STU_TIM.SAV')

# Variable Name and Label
name_label_dict = student_tim_meta.column_names_to_labels
variable = student_tim_meta.variable_value_labels

name_list = []
label_list = []
variable_list = []

for key in list(name_label_dict.keys()):
  name = key
  label = name_label_dict[key]
  name_list.append(name)
  label_list.append(label)

for key in name_list:
  try:
      # ถ้าสามารถ run ได้
      variable_bykey = variable[key]
      variable_list.append(variable_bykey)
  except:
      variable_list.append(None)

# Create Name and Label Dataset
meta_name = pd.DataFrame(name_list,columns=['Name'])
meta_value = pd.DataFrame(name_list,columns=['Name'])

meta_name['Label'] = label_list
meta_value['Value'] = variable_list

# Join meta_name and meta_value
student_tim_meta = pd.merge(meta_name, meta_value, on='Name', how='left')

In [ ]:
student_tim_meta = student_tim_meta.set_index('Name')
student_tim_meta['Name'] = name_list

student_tim_meta = student_tim_meta[['Name','Label','Value']]

print(student_tim_meta.info())
print(student_tim_meta.head(5))

<class 'pandas.core.frame.DataFrame'>
Index: 172 entries, CNT to VER_DAT
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    172 non-null    object
 1   Label   172 non-null    object
 2   Value   167 non-null    object
dtypes: object(3)
memory usage: 5.4+ KB
None
              Name                                              Label  \
Name
CNT            CNT                           Country code 3-character
CNTRYID    CNTRYID                                 Country Identifier
CNTSCHID  CNTSCHID                                    Intl. School ID
CNTSTUID  CNTSTUID                                   Intl. Student ID
CYC            CYC  PISA Assessment Cycle (2 digits + 2 character ...

                                                      Value
Name
CNT       {'MDA': 'Republic of Moldova', 'THA': 'Thailan...
CNTRYID   {8.0: 'Albania', 31.0: 'Baku (Azerbaijan)', 32...
CNTSCHID                                               None
CNTSTUID                                               None
CYC                                                    None

In [ ]:
student_tim_meta.to_excel(data_path+'student_tim_meta_2022.xlsx')

## Prepare DataFrame
`student_tim_df` already dataframe

In [ ]:
display(student_tim_df)

,CNT,CNTRYID,CNTSCHID,CNTSTUID,CYC,NatCen,STRATUM,SUBNATIO,REGION,OECD,...,WB167_TT,WB168_TT,WB171_TT,WB172_TT,WB173_TT,WB176_TT,WB177_TT,WB178_TT,WBEnd01_TT,VER_DAT
0,ALB,8.0,800282.0,800001.0,08MS,000800,ALB03,0080000,800.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03MAY23:10:11:25
1,ALB,8.0,800115.0,800002.0,08MS,000800,ALB03,0080000,800.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03MAY23:10:11:25
2,ALB,8.0,800242.0,800003.0,08MS,000800,ALB01,0080000,800.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03MAY23:10:11:25
3,ALB,8.0,800245.0,800005.0,08MS,000800,ALB08,0080000,800.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03MAY23:10:11:26
4,ALB,8.0,800285.0,800006.0,08MS,000800,ALB03,0080000,800.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03MAY23:10:11:26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
613739,UZB,860.0,86000120.0,86007488.0,08MS,086000,UZB26,8600000,86000.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02MAY23:13:18:15
613740,UZB,860.0,86000140.0,86007489.0,08MS,086000,UZB04,8600000,86000.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02MAY23:13:18:13
613741,UZB,860.0,86000024.0,86007490.0,08MS,086000,UZB10,8600000,86000.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02MAY23:13:18:13
613742,UZB,860.0,86000174.0,86007491.0,08MS,086000,UZB16,8600000,86000.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02MAY23:13:18:14
613743,UZB,860.0,86000123.0,86007492.0,08MS,086000,UZB10,8600000,86000.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02MAY23:13:18:13

In [ ]:
student_tim_df.to_csv(data_path+'student_tim_df_2022.csv')

# Finance Literacy

## COG

In [ ]:
# Import
data_path = '/content/drive/MyDrive/Data Sci CU/Research with Kiatanan/FLT_SPSS/'
fin_df, fin_meta = pyreadstat.read_sav(data_path + 'CY08MSP_FLT_COG.SAV')

# Variable Name and Label
name_label_dict = fin_meta.column_names_to_labels
variable = fin_meta.variable_value_labels

name_list = []
label_list = []
variable_list = []

for key in list(name_label_dict.keys()):
  name = key
  label = name_label_dict[key]
  name_list.append(name)
  label_list.append(label)

for key in name_list:
  try:
      # ถ้าสามารถ run ได้
      variable_bykey = variable[key]
      variable_list.append(variable_bykey)
  except:
      variable_list.append(None)

# Create Name and Label Dataset
meta_name = pd.DataFrame(name_list,columns=['Name'])
meta_value = pd.DataFrame(name_list,columns=['Name'])

meta_name['Label'] = label_list
meta_value['Value'] = variable_list

# Join meta_name and meta_value
fin_meta = pd.merge(meta_name, meta_value, on='Name', how='left')

In [ ]:
fin_meta = fin_meta.set_index('Name')
fin_meta['Name'] = name_list

fin_meta = fin_meta[['Name','Label','Value']]

print(fin_meta.info())
print(fin_meta.head(5))

<class 'pandas.core.frame.DataFrame'>
Index: 3637 entries, CNT to VER_DAT
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3637 non-null   object
 1   Label   3637 non-null   object
 2   Value   3628 non-null   object
dtypes: object(3)
memory usage: 113.7+ KB
None
              Name                                              Label  \
Name
CNT            CNT                           Country code 3-character
CNTRYID    CNTRYID                                 Country Identifier
CNTSCHID  CNTSCHID                                    Intl. School ID
CNTSTUID  CNTSTUID                                   Intl. Student ID
CYC            CYC  PISA Assessment Cycle (2 digits + 2 character ...

                                                      Value
Name
CNT       {'MDA': 'Republic of Moldova', 'THA': 'Thailan...
CNTRYID   {8.0: 'Albania', 31.0: 'Baku (Azerbaijan)', 32...
CNTSCHID                                               None
CNTSTUID                                               None
CYC                                                    None

In [ ]:
fin_meta.to_excel(data_path+'FLT_COG_meta_2022.xlsx')

In [ ]:
display(fin_df)

,CNT,CNTRYID,CNTSCHID,CNTSTUID,CYC,NatCen,STRATUM,SUBNATIO,REGION,OECD,...,CF401Q01A,CF401Q01V,CF401Q01VS,DF401Q02C,CF401Q02TT,CF401Q02F,CF401Q02A,CF401Q02V,CF401Q02VS,VER_DAT
0,AUT,40.0,4000214.0,4050001.0,08MS,004000,AUT97,0400000,4000.0,1.0,...,53.0,1.0,0.0,1.0,72912.0,19071.0,74.0,1.0,0.0,02MAY23:07:39:10
1,AUT,40.0,4000267.0,4050006.0,08MS,004000,AUT97,0400000,4000.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02MAY23:07:39:10
2,AUT,40.0,4000136.0,4050009.0,08MS,004000,AUT97,0400000,4000.0,1.0,...,5.0,1.0,0.0,NaN,114134.0,10920.0,4.0,1.0,0.0,02MAY23:07:39:12
3,AUT,40.0,4000282.0,4050010.0,08MS,004000,AUT97,0400000,4000.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02MAY23:07:39:12
4,AUT,40.0,4000173.0,4050011.0,08MS,004000,AUT97,0400000,4000.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02MAY23:07:39:10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97978,USA,840.0,84000158.0,84058152.0,08MS,084000,USA06,8400000,84000.0,1.0,...,104.0,1.0,0.0,1.0,48705.0,9795.0,69.0,1.0,0.0,02MAY23:13:08:35
97979,USA,840.0,84000097.0,84058153.0,08MS,084000,USA04,8400000,84000.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02MAY23:13:08:34
97980,USA,840.0,84000102.0,84058155.0,08MS,084000,USA06,8400000,84000.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02MAY23:13:08:35
97981,USA,840.0,84000076.0,84058156.0,08MS,084000,USA04,8400000,84000.0,1.0,...,289.0,1.0,0.0,0.0,100864.0,12399.0,137.0,1.0,0.0,02MAY23:13:08:34
97982,USA,840.0,84000044.0,84058157.0,08MS,084000,USA06,8400000,84000.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02MAY23:13:08:35

In [ ]:
fin_df.to_csv(data_path+'FLT_COG_df_2022.csv')

## QQQ

In [ ]:
# Import
data_path = '/content/drive/MyDrive/Data Sci CU/Research with Kiatanan/FLT_SPSS/'
fin_df, fin_meta = pyreadstat.read_sav(data_path + 'CY08MSP_FLT_QQQ.SAV')

# Variable Name and Label
name_label_dict = fin_meta.column_names_to_labels
variable = fin_meta.variable_value_labels

name_list = []
label_list = []
variable_list = []

for key in list(name_label_dict.keys()):
  name = key
  label = name_label_dict[key]
  name_list.append(name)
  label_list.append(label)

for key in name_list:
  try:
      # ถ้าสามารถ run ได้
      variable_bykey = variable[key]
      variable_list.append(variable_bykey)
  except:
      variable_list.append(None)

# Create Name and Label Dataset
meta_name = pd.DataFrame(name_list,columns=['Name'])
meta_value = pd.DataFrame(name_list,columns=['Name'])

meta_name['Label'] = label_list
meta_value['Value'] = variable_list

# Join meta_name and meta_value
fin_meta = pd.merge(meta_name, meta_value, on='Name', how='left')

In [ ]:
fin_meta = fin_meta.set_index('Name')
fin_meta['Name'] = name_list

fin_meta = fin_meta[['Name','Label','Value']]

print(fin_meta.info())
print(fin_meta.head(5))

<class 'pandas.core.frame.DataFrame'>
Index: 1192 entries, CNT to VER_DAT
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    1192 non-null   object
 1   Label   1192 non-null   object
 2   Value   1075 non-null   object
dtypes: object(3)
memory usage: 37.2+ KB
None
              Name                                              Label  \
Name
CNT            CNT                           Country code 3-character
CNTRYID    CNTRYID                                 Country Identifier
CNTSCHID  CNTSCHID                                    Intl. School ID
CNTSTUID  CNTSTUID                                   Intl. Student ID
CYC            CYC  PISA Assessment Cycle (2 digits + 2 character ...

                                                      Value
Name
CNT       {'MDA': 'Republic of Moldova', 'THA': 'Thailan...
CNTRYID   {8.0: 'Albania', 31.0: 'Baku (Azerbaijan)', 32...
CNTSCHID                                               None
CNTSTUID                                               None
CYC                                                    None

In [ ]:
fin_meta.to_excel(data_path+'FLT_QQQ_meta_2022.xlsx')

In [ ]:
display(fin_df)

,CNT,CNTRYID,CNTSCHID,CNTSTUID,CYC,NatCen,STRATUM,SUBNATIO,REGION,OECD,...,PV3FLIT,PV4FLIT,PV5FLIT,PV6FLIT,PV7FLIT,PV8FLIT,PV9FLIT,PV10FLIT,SENWT,VER_DAT
0,AUT,40.0,4000214.0,4050001.0,08MS,004000,AUT97,0400000,4000.0,1.0,...,568.250,563.867,638.662,587.700,611.469,594.451,609.598,586.678,1.10812,02MAY23:07:39:10
1,AUT,40.0,4000267.0,4050006.0,08MS,004000,AUT97,0400000,4000.0,1.0,...,420.480,424.382,461.258,483.665,484.476,492.257,465.653,454.554,1.64799,02MAY23:07:39:10
2,AUT,40.0,4000136.0,4050009.0,08MS,004000,AUT97,0400000,4000.0,1.0,...,395.616,345.146,369.343,386.411,390.050,410.587,361.884,365.359,1.03185,02MAY23:07:39:12
3,AUT,40.0,4000282.0,4050010.0,08MS,004000,AUT97,0400000,4000.0,1.0,...,464.942,467.622,462.535,392.837,444.827,484.985,526.083,451.014,1.69094,02MAY23:07:39:12
4,AUT,40.0,4000173.0,4050011.0,08MS,004000,AUT97,0400000,4000.0,1.0,...,524.071,442.481,497.974,505.421,523.223,478.699,538.202,538.901,2.24727,02MAY23:07:39:10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97978,USA,840.0,84000158.0,84058152.0,08MS,084000,USA06,8400000,84000.0,1.0,...,479.890,442.003,498.238,449.045,485.437,460.034,470.623,512.251,1.23025,02MAY23:13:08:35
97979,USA,840.0,84000097.0,84058153.0,08MS,084000,USA04,8400000,84000.0,1.0,...,539.871,550.474,553.615,576.269,527.033,549.972,592.595,511.053,1.64700,02MAY23:13:08:34
97980,USA,840.0,84000102.0,84058155.0,08MS,084000,USA06,8400000,84000.0,1.0,...,252.183,319.845,303.307,336.800,270.313,281.668,273.596,338.350,1.94989,02MAY23:13:08:35
97981,USA,840.0,84000076.0,84058156.0,08MS,084000,USA04,8400000,84000.0,1.0,...,609.265,614.346,547.348,557.261,576.436,645.575,566.652,609.402,1.59683,02MAY23:13:08:34
97982,USA,840.0,84000044.0,84058157.0,08MS,084000,USA06,8400000,84000.0,1.0,...,405.397,459.935,460.010,457.559,474.932,518.939,471.448,596.975,1.79973,02MAY23:13:08:35

In [ ]:
fin_df.to_csv(data_path+'FLT_QQQ_df_2022.csv')

## TIM

In [ ]:
# Import
data_path = '/content/drive/MyDrive/Data Sci CU/Research with Kiatanan/FLT_SPSS/'
fin_df, fin_meta = pyreadstat.read_sav(data_path + 'CY08MSP_FLT_TIM.SAV')

# Variable Name and Label
name_label_dict = fin_meta.column_names_to_labels
variable = fin_meta.variable_value_labels

name_list = []
label_list = []
variable_list = []

for key in list(name_label_dict.keys()):
  name = key
  label = name_label_dict[key]
  name_list.append(name)
  label_list.append(label)

for key in name_list:
  try:
      # ถ้าสามารถ run ได้
      variable_bykey = variable[key]
      variable_list.append(variable_bykey)
  except:
      variable_list.append(None)

# Create Name and Label Dataset
meta_name = pd.DataFrame(name_list,columns=['Name'])
meta_value = pd.DataFrame(name_list,columns=['Name'])

meta_name['Label'] = label_list
meta_value['Value'] = variable_list

# Join meta_name and meta_value
fin_meta = pd.merge(meta_name, meta_value, on='Name', how='left')

In [ ]:
fin_meta = fin_meta.set_index('Name')
fin_meta['Name'] = name_list

fin_meta = fin_meta[['Name','Label','Value']]

print(fin_meta.info())
print(fin_meta.head(5))

<class 'pandas.core.frame.DataFrame'>
Index: 172 entries, CNT to VER_DAT
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    172 non-null    object
 1   Label   172 non-null    object
 2   Value   167 non-null    object
dtypes: object(3)
memory usage: 5.4+ KB
None
              Name                                              Label  \
Name
CNT            CNT                           Country code 3-character
CNTRYID    CNTRYID                                 Country Identifier
CNTSCHID  CNTSCHID                                    Intl. School ID
CNTSTUID  CNTSTUID                                   Intl. Student ID
CYC            CYC  PISA Assessment Cycle (2 digits + 2 character ...

                                                      Value
Name
CNT       {'MDA': 'Republic of Moldova', 'THA': 'Thailan...
CNTRYID   {8.0: 'Albania', 31.0: 'Baku (Azerbaijan)', 32...
CNTSCHID                                               None
CNTSTUID                                               None
CYC                                                    None

In [ ]:
fin_meta.to_excel(data_path+'FLT_TIM_meta_2022.xlsx')

In [ ]:
display(fin_df)

,CNT,CNTRYID,CNTSCHID,CNTSTUID,CYC,NatCen,STRATUM,SUBNATIO,REGION,OECD,...,WB167_TT,WB168_TT,WB171_TT,WB172_TT,WB173_TT,WB176_TT,WB177_TT,WB178_TT,WBEnd01_TT,VER_DAT
0,AUT,40.0,4000214.0,4050001.0,08MS,004000,AUT97,0400000,4000.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02MAY23:07:39:10
1,AUT,40.0,4000267.0,4050006.0,08MS,004000,AUT97,0400000,4000.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02MAY23:07:39:10
2,AUT,40.0,4000136.0,4050009.0,08MS,004000,AUT97,0400000,4000.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02MAY23:07:39:12
3,AUT,40.0,4000282.0,4050010.0,08MS,004000,AUT97,0400000,4000.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02MAY23:07:39:12
4,AUT,40.0,4000173.0,4050011.0,08MS,004000,AUT97,0400000,4000.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02MAY23:07:39:10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97978,USA,840.0,84000158.0,84058152.0,08MS,084000,USA06,8400000,84000.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02MAY23:13:08:35
97979,USA,840.0,84000097.0,84058153.0,08MS,084000,USA04,8400000,84000.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02MAY23:13:08:34
97980,USA,840.0,84000102.0,84058155.0,08MS,084000,USA06,8400000,84000.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02MAY23:13:08:35
97981,USA,840.0,84000076.0,84058156.0,08MS,084000,USA04,8400000,84000.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02MAY23:13:08:34
97982,USA,840.0,84000044.0,84058157.0,08MS,084000,USA06,8400000,84000.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02MAY23:13:08:35

In [ ]:
fin_df.to_csv(data_path+'FLT_TIM_df_2022.csv')

# Creative Thinking

## Prepare Meta Data

In [ ]:
# Import
data_path = '/content/drive/MyDrive/Data Sci CU/Research with Kiatanan/Creative Thinking data file/'
df, meta = pyreadstat.read_sav(data_path + 'CY08MSP_CRT_COG.SAV')

# Variable Name and Label
name_label_dict = meta.column_names_to_labels
variable = meta.variable_value_labels

name_list = []
label_list = []
variable_list = []

for key in list(name_label_dict.keys()):
  name = key
  label = name_label_dict[key]
  name_list.append(name)
  label_list.append(label)

for key in name_list:
  try:
      # ถ้าสามารถ run ได้
      variable_bykey = variable[key]
      variable_list.append(variable_bykey)
  except:
      variable_list.append(None)

# Create Name and Label Dataset
meta_name = pd.DataFrame(name_list,columns=['Name'])
meta_value = pd.DataFrame(name_list,columns=['Name'])

meta_name['Label'] = label_list
meta_value['Value'] = variable_list

# Join meta_name and meta_value
meta = pd.merge(meta_name, meta_value, on='Name', how='left')

In [ ]:
meta = meta.set_index('Name')
meta['Name'] = name_list

meta = meta[['Name','Label','Value']]

print(meta.info())
print(meta.head(5))

<class 'pandas.core.frame.DataFrame'>
Index: 301 entries, CNT to VER_DAT
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    301 non-null    object
 1   Label   301 non-null    object
 2   Value   257 non-null    object
dtypes: object(3)
memory usage: 9.4+ KB
None
              Name                                              Label  \
Name
CNT            CNT                           Country code 3-character
CNTRYID    CNTRYID                                 Country Identifier
CNTSCHID  CNTSCHID                                    Intl. School ID
CNTSTUID  CNTSTUID                                   Intl. Student ID
CYC            CYC  PISA Assessment Cycle (2 digits + 2 character ...

                                                      Value
Name
CNT       {'MDA': 'Republic of Moldova', 'THA': 'Thailan...
CNTRYID   {8.0: 'Albania', 31.0: 'Baku (Azerbaijan)', 32...
CNTSCHID                                               None
CNTSTUID                                               None
CYC                                                    None

In [ ]:
meta.to_excel(data_path+'CLT_meta_2022.xlsx')

In [ ]:
display(df)

,CNT,CNTRYID,CNTSCHID,CNTSTUID,CYC,NatCen,STRATUM,SUBNATIO,REGION,OECD,...,PV2SCIC,PV3SCIC,PV4SCIC,PV5SCIC,PV6SCIC,PV7SCIC,PV8SCIC,PV9SCIC,PV10SCIC,VER_DAT
0,ALB,8.0,800282.0,800001.0,08MS,000800,ALB03,0080000,800.0,0.0,...,262.385,378.234,233.257,212.156,233.964,309.614,279.121,307.371,254.094,03MAY23:10:11:25
1,ALB,8.0,800115.0,800002.0,08MS,000800,ALB03,0080000,800.0,0.0,...,342.949,272.317,322.197,313.890,276.797,285.500,272.011,285.815,303.112,03MAY23:10:11:25
2,ALB,8.0,800242.0,800003.0,08MS,000800,ALB01,0080000,800.0,0.0,...,263.749,326.726,312.912,347.302,365.408,289.463,322.651,301.664,318.171,03MAY23:10:11:25
3,ALB,8.0,800245.0,800005.0,08MS,000800,ALB08,0080000,800.0,0.0,...,217.620,188.429,251.718,221.253,224.181,236.108,186.181,210.124,202.408,03MAY23:10:11:26
4,ALB,8.0,800285.0,800006.0,08MS,000800,ALB03,0080000,800.0,0.0,...,397.855,371.548,475.899,513.049,496.343,470.011,485.648,424.060,479.116,03MAY23:10:11:26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499838,UZB,860.0,86000120.0,86007488.0,08MS,086000,UZB26,8600000,86000.0,0.0,...,220.570,339.730,306.908,304.665,267.158,297.498,253.395,299.630,327.294,02MAY23:13:18:15
499839,UZB,860.0,86000140.0,86007489.0,08MS,086000,UZB04,8600000,86000.0,0.0,...,298.729,271.548,322.417,320.433,259.321,310.992,304.170,268.460,255.466,02MAY23:13:18:13
499840,UZB,860.0,86000024.0,86007490.0,08MS,086000,UZB10,8600000,86000.0,0.0,...,375.685,372.132,429.488,389.984,379.921,341.487,338.657,374.555,421.512,02MAY23:13:18:13
499841,UZB,860.0,86000174.0,86007491.0,08MS,086000,UZB16,8600000,86000.0,0.0,...,418.228,356.431,341.121,360.830,411.116,350.535,424.575,418.980,357.175,02MAY23:13:18:14
499842,UZB,860.0,86000123.0,86007492.0,08MS,086000,UZB10,8600000,86000.0,0.0,...,447.746,388.369,378.244,355.728,387.404,399.308,421.224,412.867,405.144,02MAY23:13:18:13

In [ ]:
df.to_csv(data_path+'CLT_df_2022.csv')

# Student Cog

In [ ]:
# Import
data_path = '/content/drive/MyDrive/Data Sci CU/Research with Kiatanan/Cognitive item data file/'
df, meta = pyreadstat.read_sav(data_path + 'CY08MSP_STU_COG.SAV')

# Variable Name and Label
name_label_dict = meta.column_names_to_labels
variable = meta.variable_value_labels

name_list = []
label_list = []
variable_list = []

for key in list(name_label_dict.keys()):
  name = key
  label = name_label_dict[key]
  name_list.append(name)
  label_list.append(label)

for key in name_list:
  try:
      # ถ้าสามารถ run ได้
      variable_bykey = variable[key]
      variable_list.append(variable_bykey)
  except:
      variable_list.append(None)

# Create Name and Label Dataset
meta_name = pd.DataFrame(name_list,columns=['Name'])
meta_value = pd.DataFrame(name_list,columns=['Name'])

meta_name['Label'] = label_list
meta_value['Value'] = variable_list

# Join meta_name and meta_value
meta = pd.merge(meta_name, meta_value, on='Name', how='left')